### ISSUE TITLE
If a user is already a collaborator to an app (even if it's just view permissions) this script fails

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/heroku-permissions#31]
Heroku have changed their API (fair enough because it wasn't documented).  You used to be able to ‘upsert’.  Now we're going to need either send a `PATCH` to `https://api.heroku.com/organizations/apps/"+app+"/collaborators/email.address@ft.com` if the user is already a collaborator to the app or follow the current logic if they are not.

https://github.com/Financial-Times/heroku-permissions/blob/master/heroku/heroku.go#L115-L118

**Comment by matthew-andrews** [comment]
A workaround:-
- Remove all the developers from your dev sheet (leaving one admin, e.g. matthew.andrews@ft.com) + republish
- Run the heroku permissions script (revoking everyone from all of your apps)
- Re-add the developers to the dev sheet + republish
- Run the heroku permissions script (adding everyone to all of your apps)

**Comment by bjfletcher** [comment]
All I needed to do was to run:

`heroku apps:leave --app ft-stream-branch-2233`

and then rerun the script.

**Comment by adambraimbridge** [comment]
I volunteer my emotional support, if not technical support (I think it's a bit beyond me TBH)
